//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChungCu
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietcanho
    {
        public Nullable<int> macanho { get; set; }
        public string vatdung { get; set; }
        public int soluong { get; set; }
        public double dongia { get; set; }
    
        public virtual canho canho { get; set; }
    }
}
