//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChungCu
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethoadon
    {
        public int mahoadon { get; set; }
        public int madichvu { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual dichvu dichvu { get; set; }
        public virtual hoadondichvu hoadondichvu { get; set; }
    }
}
