//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChungCu
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        public string tendangnhap { get; set; }
        public Nullable<int> manhanvien { get; set; }
        public string matkhau { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
